version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app-backend"
    schedule:
      interval: "daily"
    labels:
      - "gradle"
      - "dependencies"

  - package-ecosystem: "npm"
    directory: "/app-frontend"
    schedule:
      interval: "daily"
    labels:
      - "npm"
      - "dependencies"